/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package accord.local;

import java.util.EnumMap;

import accord.utils.Invariants;

// TODO (desired): is there a better way to represent these states? can we (for instance) collapse WAS_OWNED to a bit flag
//  Consider: can we collapse all PARTIALLY_LOCALLY states into simply LOCALLY? Since we know the transaction must be redundant in this case.
public enum RedundantStatus
{
    /**
     * None of the relevant ranges are owned by the command store
     */
    NOT_OWNED,

    /**
     * None of the relevant ranges are owned by the command store anymore
     */
    WAS_OWNED,

    /**
     * None of the relevant ranges are owned by the command store anymore, and all of those ranges are closed
     * (i.e. we should know all participating commands already)
     */
    WAS_OWNED_CLOSED,

    /**
     * None of the relevant ranges are owned by the command store anymore, and at least some of those ranges are
     * retired locally.
     * (i.e. we should not expect any knowledge of such a transaction)
     * TODO (desired): do we need this state?
     */
    WAS_OWNED_PARTIALLY_RETIRED,

    /**
     * None of the relevant ranges are owned by the command store anymore, and all of those ranges are retired
     * at all healthy participating replicas
     * (i.e. we should not participate in any decisions)
     */
    WAS_OWNED_RETIRED,

    /**
     * Some of the relevant ranges are owned by the command store and valid for execution
     */
    LIVE,

    /**
     * The relevant owned ranges are part live and part pre-bootstrap or stale
     */
    PARTIALLY_PRE_BOOTSTRAP_OR_STALE,

    /**
     * The relevant owned ranges are ALL pre-bootstrap or stale, meaning we are either
     *  1) fetching the transaction's entire result from another node's snapshot already; or
     *  2) the range is stale and _must be bootstrapped_
     */
    PRE_BOOTSTRAP_OR_STALE,

    /**
     * Some of the relevant owned ranges are redundant, meaning any intersecting transaction is known to be either applied
     * or invalidated via a sync point that has applied locally, but other ranges may be pre-bootstrap or stale,
     * so that we cannot treat the transaction as having been fully applied locally, and other ranges may still be LIVE
     * so that we cannot fully cleanup the transaction.
     *
     * Note that this status overrides PRE_BOOTSTRAP_OR_STALE, since it implies the transaction has applied.
     */
    PARTIALLY_LOCALLY_REDUNDANT,

    /**
     * The relevant owned ranges are redundant, meaning any intersecting transaction is known to be either applied or invalidated
     * via a sync point that has applied locally.
     *
     * Note that this status overrides PRE_BOOTSTRAP_OR_STALE, since it implies the transaction has applied.
     */
    LOCALLY_REDUNDANT,

    /**
     * The relevant owned ranges are all shard-redundant AND (pre-bootstrap or stale), meaning any intersecting transaction
     * is known to be either applied or invalidated via a sync point that has applied locally AND on all healthy shards.
     * But the transaction may not have been maintained locally.
     */
    SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE,

    /**
     * Some of the relevant owned ranges are redundant, meaning any intersecting transaction is known to be either applied
     * or invalidated via a sync point that has applied locally AND on all healthy shards.
     */
    PARTIALLY_SHARD_REDUNDANT,

    /**
     * Some of the relevant owned ranges are redundant, meaning any intersecting transaction is known to be either applied
     * or invalidated via a sync point that has applied locally AND on all healthy shards.
     * TODO (desired): do we need this state?
     */
    PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT,

    /**
     * The relevant owned ranges are redundant, meaning any intersecting transaction is known to be either applied or invalidated
     * via a sync point that has applied locally AND on all healthy shards. Note that this status CANNOT be taken if
     * we are not ALSO LOCALLY_REDUNDANT, so we can use this to cleanup transactions < PreCommitted (or Erased).
     *
     * Note that this status overrides PRE_BOOTSTRAP_OR_STALE, since it implies the transaction has applied.
     */
    SHARD_REDUNDANT,

    /**
     * All of the relevant owned ranges are either shard redundant and pre-bootstrap Or gc-able, meaning any intersecting
     * transaction is known to be applied at a majority of the shard, or invalidated via a sync point that we have
     * applied locally, and that we do not need to know anymore about the command's outcome ourselves and may erase it.
     */
    GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE,

    /**
     * The relevant owned ranges are redundant, meaning any intersecting transaction is known to be either applied or invalidated
     * via a sync point that has applied locally AND on all healthy shards. Note that this status CANNOT be taken if
     * we are not ALSO LOCALLY_REDUNDANT, so we can use this to cleanup local state.
     *
     * Note that this status overrides PRE_BOOTSTRAP_OR_STALE, since it implies the transaction has applied.
     */
    GC_BEFORE,
    ;

    private EnumMap<RedundantStatus, RedundantStatus> merge;

    static
    {
        NOT_OWNED.merge = new EnumMap<>(RedundantStatus.class);
        NOT_OWNED.merge.put(NOT_OWNED, NOT_OWNED);
        NOT_OWNED.merge.put(WAS_OWNED, WAS_OWNED);
        NOT_OWNED.merge.put(WAS_OWNED_CLOSED, WAS_OWNED_CLOSED);
        NOT_OWNED.merge.put(WAS_OWNED_PARTIALLY_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        NOT_OWNED.merge.put(WAS_OWNED_RETIRED, WAS_OWNED_RETIRED);
        NOT_OWNED.merge.put(LIVE, LIVE);
        NOT_OWNED.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        NOT_OWNED.merge.put(PRE_BOOTSTRAP_OR_STALE, PRE_BOOTSTRAP_OR_STALE);
        NOT_OWNED.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        NOT_OWNED.merge.put(LOCALLY_REDUNDANT, LOCALLY_REDUNDANT);
        NOT_OWNED.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        NOT_OWNED.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        NOT_OWNED.merge.put(SHARD_REDUNDANT, SHARD_REDUNDANT);
        NOT_OWNED.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        NOT_OWNED.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        NOT_OWNED.merge.put(GC_BEFORE, GC_BEFORE);
        WAS_OWNED.merge = new EnumMap<>(RedundantStatus.class);
        WAS_OWNED.merge.put(NOT_OWNED, WAS_OWNED);
        WAS_OWNED.merge.put(WAS_OWNED, WAS_OWNED);
        WAS_OWNED.merge.put(WAS_OWNED_CLOSED, WAS_OWNED);
        WAS_OWNED.merge.put(WAS_OWNED_PARTIALLY_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED.merge.put(WAS_OWNED_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED.merge.put(LIVE, LIVE);
        WAS_OWNED.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_CLOSED.merge = new EnumMap<>(RedundantStatus.class);
        WAS_OWNED_CLOSED.merge.put(NOT_OWNED, WAS_OWNED_CLOSED);
        WAS_OWNED_CLOSED.merge.put(WAS_OWNED, WAS_OWNED);
        WAS_OWNED_CLOSED.merge.put(WAS_OWNED_CLOSED, WAS_OWNED_CLOSED);
        WAS_OWNED_CLOSED.merge.put(WAS_OWNED_PARTIALLY_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_CLOSED.merge.put(WAS_OWNED_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_CLOSED.merge.put(LIVE, LIVE);
        WAS_OWNED_CLOSED.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_CLOSED.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_CLOSED.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_CLOSED.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge = new EnumMap<>(RedundantStatus.class);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(NOT_OWNED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(WAS_OWNED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(WAS_OWNED_CLOSED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(WAS_OWNED_PARTIALLY_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(WAS_OWNED_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(LIVE, LIVE);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(PRE_BOOTSTRAP_OR_STALE, PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_PARTIALLY_RETIRED.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_RETIRED.merge = new EnumMap<>(RedundantStatus.class);
        WAS_OWNED_RETIRED.merge.put(NOT_OWNED, WAS_OWNED_RETIRED);
        WAS_OWNED_RETIRED.merge.put(WAS_OWNED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_RETIRED.merge.put(WAS_OWNED_CLOSED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_RETIRED.merge.put(WAS_OWNED_PARTIALLY_RETIRED, WAS_OWNED_PARTIALLY_RETIRED);
        WAS_OWNED_RETIRED.merge.put(WAS_OWNED_RETIRED, WAS_OWNED_RETIRED);
        WAS_OWNED_RETIRED.merge.put(LIVE, LIVE);
        WAS_OWNED_RETIRED.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_RETIRED.merge.put(PRE_BOOTSTRAP_OR_STALE, PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_RETIRED.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        WAS_OWNED_RETIRED.merge.put(LOCALLY_REDUNDANT, LOCALLY_REDUNDANT);
        WAS_OWNED_RETIRED.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        WAS_OWNED_RETIRED.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        WAS_OWNED_RETIRED.merge.put(SHARD_REDUNDANT, SHARD_REDUNDANT);
        WAS_OWNED_RETIRED.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_RETIRED.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        WAS_OWNED_RETIRED.merge.put(GC_BEFORE, GC_BEFORE);
        LIVE.merge = new EnumMap<>(RedundantStatus.class);
        LIVE.merge.put(NOT_OWNED, LIVE);
        LIVE.merge.put(WAS_OWNED, LIVE);
        LIVE.merge.put(WAS_OWNED_CLOSED, LIVE);
        LIVE.merge.put(WAS_OWNED_PARTIALLY_RETIRED, LIVE);
        LIVE.merge.put(WAS_OWNED_RETIRED, LIVE);
        LIVE.merge.put(LIVE, LIVE);
        LIVE.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        LIVE.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        LIVE.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        LIVE.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        LIVE.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        LIVE.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        LIVE.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        LIVE.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        LIVE.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        LIVE.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge = new EnumMap<>(RedundantStatus.class);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(NOT_OWNED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_CLOSED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_RETIRED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(LIVE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge = new EnumMap<>(RedundantStatus.class);
        PRE_BOOTSTRAP_OR_STALE.merge.put(NOT_OWNED, PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_CLOSED, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_RETIRED, PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(LIVE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(PRE_BOOTSTRAP_OR_STALE, PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PRE_BOOTSTRAP_OR_STALE);
        PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge = new EnumMap<>(RedundantStatus.class);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(NOT_OWNED, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED_CLOSED, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED_RETIRED, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(LIVE, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_LOCALLY_REDUNDANT.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        LOCALLY_REDUNDANT.merge = new EnumMap<>(RedundantStatus.class);
        LOCALLY_REDUNDANT.merge.put(NOT_OWNED, LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(WAS_OWNED, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(WAS_OWNED_CLOSED, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(WAS_OWNED_RETIRED, LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(LIVE, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(LOCALLY_REDUNDANT, LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        LOCALLY_REDUNDANT.merge.put(GC_BEFORE, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge = new EnumMap<>(RedundantStatus.class);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(NOT_OWNED, SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_CLOSED, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_RETIRED, SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(LIVE, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PRE_BOOTSTRAP_OR_STALE, PRE_BOOTSTRAP_OR_STALE);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT, SHARD_REDUNDANT);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        PARTIALLY_SHARD_REDUNDANT.merge = new EnumMap<>(RedundantStatus.class);
        PARTIALLY_SHARD_REDUNDANT.merge.put(NOT_OWNED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(WAS_OWNED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(WAS_OWNED_CLOSED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(WAS_OWNED_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(LIVE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_REDUNDANT.merge.put(GC_BEFORE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge = new EnumMap<>(RedundantStatus.class);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(NOT_OWNED, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED_CLOSED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(WAS_OWNED_RETIRED, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(LIVE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(SHARD_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT.merge.put(GC_BEFORE, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        SHARD_REDUNDANT.merge = new EnumMap<>(RedundantStatus.class);
        SHARD_REDUNDANT.merge.put(NOT_OWNED, SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(WAS_OWNED, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(WAS_OWNED_CLOSED, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(WAS_OWNED_RETIRED, SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(LIVE, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        // TODO (required): we merge LOCALLY_REDUNDANT and PARTIALLY_LOCALLY_REDUNDANT inconsistently.
        //   Consider: do we ever need to know LOCALLY_REDUNDANT *and* PARTIALLY_SHARD_REDUNDANT?
        SHARD_REDUNDANT.merge.put(LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        SHARD_REDUNDANT.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        SHARD_REDUNDANT.merge.put(SHARD_REDUNDANT, SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, SHARD_REDUNDANT);
        SHARD_REDUNDANT.merge.put(GC_BEFORE, SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge = new EnumMap<>(RedundantStatus.class);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(NOT_OWNED, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_CLOSED, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(WAS_OWNED_RETIRED, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(LIVE, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT, SHARD_REDUNDANT);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE.merge.put(GC_BEFORE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE.merge = new EnumMap<>(RedundantStatus.class);
        GC_BEFORE.merge.put(NOT_OWNED, GC_BEFORE);
        GC_BEFORE.merge.put(WAS_OWNED, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(WAS_OWNED_CLOSED, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(WAS_OWNED_PARTIALLY_RETIRED, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(WAS_OWNED_RETIRED, GC_BEFORE);
        GC_BEFORE.merge.put(LIVE, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(PARTIALLY_PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(PRE_BOOTSTRAP_OR_STALE, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(PARTIALLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        GC_BEFORE.merge.put(PARTIALLY_SHARD_REDUNDANT, PARTIALLY_SHARD_REDUNDANT);
        GC_BEFORE.merge.put(PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT, PARTIALLY_SHARD_FULLY_LOCALLY_REDUNDANT);
        GC_BEFORE.merge.put(SHARD_REDUNDANT, SHARD_REDUNDANT);
        GC_BEFORE.merge.put(SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE.merge.put(GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE, GC_BEFORE_OR_SHARD_REDUNDANT_AND_PRE_BOOTSTRAP_OR_STALE);
        GC_BEFORE.merge.put(GC_BEFORE, GC_BEFORE);

        for (RedundantStatus a : values())
        {
            for (RedundantStatus b : values())
            {
                Invariants.checkState(a.merge(b) == b.merge(a), "non-symmetric merge of %s and %s", a, b);
            }
        }
    }

    public RedundantStatus merge(RedundantStatus that)
    {
        RedundantStatus result = merge.get(that);
        Invariants.checkState(result != null, "Invalid RedundantStatus combination: " + this + " and " + that);
        return result;
    }
}
